# Site settings
title: "Alessandro Sforzin Homepage"
description: "Alessandro Sforzin Curriculum Vitae"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Alessandro Sforzin"
resume_title:                   "Distributed Systems Engineer, Go Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "lisasimpson@youremailaddress.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: <p>As a software engineer with a track record of successfully transferring R&D projects into corporate products, I thrive in fast-paced environments and enjoy working with researchers and business units to turn abstract ideas into tangible solutions. My skills in identifying requirements and managing time effectively have proven invaluable in my work with state-of-the-art security research and technologies. My passion lies in secure distributed systems R&D using Go, and I'm always eager to expand my knowledge and skills. I possess excellent communication skills and thrive in team environments where collaboration and innovation are encouraged. Recently, I've been engaging in the <a href="https://cryptopals.com">Matasano Cryptopals</a> cryptography challenges; it's good fun.</p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_awards:          true
resume_section_education:       true
resume_section_experience:      true
resume_section_patents:         true
resume_section_publications:    true
resume_section_skills:          true
# resume_section_associations:    true
# resume_section_projects:        true
# resume_section_links:           true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/alesforz"
  # resume_twitter_url:           "http://twitter.com/"
  # resume_dribbble_url:          "https://dribbble.com/"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/alesforz/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/"
  resume_scholar_url:           "https://shorturl.at/wCH38"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
