# Site settings
title: "Alessandro Sforzin - Lead Software Engineer"
description: "CV of a 8-year-experienced Distributed Systems Engineer based in Heidelberg, Germany"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Alessandro Sforzin"
resume_title:                   "Distributed Systems Engineer, Go Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "mail@alesforz.eu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

# resume_header_contact_info:     "Heidelberg, Germany • 555-7334 • lisasimpson@youremailaddress.com"
resume_header_contact_info:     "🇮🇹 born in 1988 • Based in Heidelberg 🇩🇪"
display_header_contact_info:    "true"

resume_header_intro: >
  <p>Hey there!
  I'm a software engineer excited about transforming innovative research projects into reality.
  I thrive in a collaborative environment and enjoy working with both researchers and business teams to turn abstract ideas into practical solutions.
  You'll often find me knee-deep in creating software using Go, which is my favorite programming language! My expertise lies in secure distributed systems and I'm continuously eager to expand my knowledge and skills. My contributions haven't gone unnoticed: my work has been recognized through awards and patents that I'm really proud of.<br>
  When I'm not programming, you'll find me exploring different worlds through books, baking gluten-free stuff, or attempting to lift heavy things (and then putting them down).<br>
  I'm always on the lookout for the next big challenge and a fresh cup of espresso to start my day!<br><br>
  So, what brings you here today?</p>


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_awards:          true
resume_section_education:       true
resume_section_experience:      true
resume_section_patents:         true
resume_section_publications:    true
resume_section_skills:          true
# resume_section_associations:    true
# resume_section_projects:        true
# resume_section_links:           true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/alesforz"
  # resume_twitter_url:           "http://twitter.com/"
  # resume_dribbble_url:          "https://dribbble.com/"
  resume_facebook_url:          "https://www.facebook.com/alessandro.sforzin"
  resume_linkedin_url:          "https://www.linkedin.com/in/alesforz/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/"
  resume_scholar_url:           "https://shorturl.at/wCH38"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
